import sys

objs = []

walls = [[  0.0,   0.0,  2.0,100.0,180.0, 39.0,  4.0],
         [ 14.5,  18.0,  2.0, 48.0, 48.0,  5.0,  1.5],
         [  7.0,  10.5,  2.0, 63.0, 63.0, 16.0,  1.5],
         [  2.0,   2.0, 41.0, 96.0,176.0,  2.0,  2.0]]
boxes = [[100.0, 180.0,  4.0,  0.0,  0.0,  0.0]]
# USB téléphone + connecteurs USB/Ethernet
deboxes = [#[ 11.0,   8.0,  6.5, 44.5, 175.0,  37.0],
           [  3.0,  11.5,  9.0,  1.01,  36.95,18.3],
           [  58.0,  3.5,  2.5,  18.0-5.08,175.0, 17.5],
           [  16.1,  3.5, 15.0,  56.0-5.08,176.0, 19.9],
           [  15.1,  3.5, 15.8,  38.1-5.08,176.0, 20.4],
           [  15.1,  3.5, 15.8,  19.5-5.08,176.0, 20.4]]

screws = [ [  6.0,   6.0, 33.0],
		   [  6.0, 174.0, 33.0],
		   [ 94.0,   6.0, 33.0],
		   [ 94.0, 174.0, 33.0]]

'''
connectors = [ [  16.1,  3.5, 15.0,  36.5,  0.0,  0.0],
               [  15.1,  3.5, 16.5,  18.6,  0.0,  0.5],
               [  15.1,  3.5, 16.5,   0.0,  0.0,  0.5]]
'''
n = 0
for b in walls:
    
    shapeObj = "translate("+str(b[0:3])+") cube("+str([b[3]-b[6],b[6],b[5]]) + ")"
    objs.append(shapeObj)
    n += 1

    shapeObj = "translate("+str([b[0],b[1]+b[6],b[2]])+") cube("+str([b[6],b[4]-b[6]-b[6],b[5]]) + ")"
    objs.append(shapeObj)
    n += 1

    shapeObj = "translate("+str([b[0]+b[3]-b[6],b[1],b[2]])+") cube("+str([b[6],b[4],b[5]]) + ")"
    objs.append(shapeObj)
    n += 1

    shapeObj = "translate("+str([b[0],b[1]+b[4]-b[6],b[2]])+") cube("+str([b[3]-b[6],b[6],b[5]]) + ")"
    objs.append(shapeObj)
    n += 1

# end for

for b in boxes:
    shapeObj = "translate("+str(b[3:6])+") cube("+str(b[0:3]) + ")"
    objs.append(shapeObj)
    n += 1
# end for

shapeObj = "union() {\n"
for o in objs:
    shapeObj += "  " + o + ";\n"
# end for

holes = [[ 7.0,  20.0, 4.0],
         [ 7.0,  64.5, 4.0],
         [70.0,  20.0, 4.0],
         [70.0,  64.5, 4.0],
         [85.0,  35.0, 4.0],
         [85.0,  65.0, 4.0],
         [21.2+1.35-5.08,180-25.8, 4.0],
         [21.2+1.35+48.9-5.08,180-25.8, 4.0],
         [21.2+1.35-5.08,180-25.8-57.8, 4.0],
         [21.2+1.35+48.9-5.08,180-25.8-57.8, 4.0]]
      
for d in holes:
    shapeObj += "difference() {\n  "
    shapeObj += "translate("+str(d[0:3])+") cylinder(15,r=3.1);\n "
    shapeObj += "translate("+str([d[0],d[1],d[2]+11.0])+") cylinder(4,r=1);\n}\n"
#    objs.append(shapeObj)
# end for

for d in screws:
    shapeObj += " translate("+str([d[0]-3.0,d[1]-3.0,2.0])+") cube("+str([6.0,6.0,41.0]) + ");\n"
# end for

shapeObj += "}\n"
objs = [shapeObj]


shapeObj = "difference() {\n"  + objs[0]

# On/Off button hole
shapeObj += "translate("+str([100.0-4,48.0-7.0,19.0])+") cube("+str([3.0,14.0,4.0]) + ");\n"

for d in deboxes:
    shapeObj += "translate("+str(d[3:6])+") cube("+str(d[0:3]) + ");\n"
    # shapeObj += "translate("+str([b[3]+19.5,b[4]+179.5-b[1],b[5]+19.3])+") cube("+str(b[0:3]) + ");\n"
# end for


for d in screws:
    #shapeObj += "union() {\n  "
    shapeObj += "translate("+str(d[0:3])+") cylinder(10,r=1.5);\n  "
    # shapeObj += "translate("+str(d[0:3])+") cylinder(3,r1=3,r2=0);\n}\n"
# end for
'''
for b in connectors:
    # Z : 20.4 en dessous du bord le plus bas
    shapeObj += "translate("+str([b[3]+19.5,b[4]+179.5-b[1],b[5]+19.3])+") cube("+str(b[0:3]) + ");\n"
# end for
'''


shapeObj += "}\n"

objs = [shapeObj]

main = 0

print("// Do not edit this file :")
print("// this file has been generated by " + sys.argv[0])
print("$fn = 50;")
for s in objs:
    if s is not None:
        print(s+";")
    
sys.exit(0)

doc.recompute()
